validation rules part2
Energinet-DataHub/geh-metering-point pull request #107
Opened 2021-05-25 14:20 UTC by xnetsrak

## Description

Validation errors, validation rules and Error Converters added for:

CityName
MeteringGridArea
MeteringPointType
OccurenceDate
PostCode
StreetName

## References

* #71

2021-05-25 17:25 UTC, cmgrd requested changes

2021-05-25 17:25 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/OccurenceDateValidRule.cs
> +        private const string OccurenceDateFormatRexEx = @"^(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})Z$";
nit: typo ...RexEx

2021-05-25 17:25 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/OccurenceDateValidRule.cs
> +        private const string OccurenceDateFormatRexEx = @"^(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})Z$";
In #71 OccurenceDate is mentioned twice; both with local and UTC, we need to figure out which it is.

2021-05-25 17:25 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/OccurenceDateValidRule.cs
> +    public class OccurenceDateValidRule : AbstractValidator<CreateMeteringPoint>
nit: other rules are named ...MustBeValidRule

2021-05-25 17:46 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/CityNameMustBeValidRule.cs
> +                .WithState(createMeteringPoint => new MandatoryFieldForMeteringPointTypeValidationError(nameof(createMeteringPoint.InstallationLocationAddress.CityName), createMeteringPoint.TypeOfMet
The error codes are per rule and not per field. So multiple per field

2021-05-25 17:47 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/OccurenceDateValidRule.cs
> +        private const string OccurenceDateFormatRexEx = @"^(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})Z$";
It is utc. So an occurrence for a specific date, eg 24th, would appear as 23rd at 22.00.00z

2021-05-26 19:17 UTC, MrDach commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/PostCodeFormatMustBeValidRule.cs
> +        private const string PostCodeDkFormatRegEx = @"^([0-9]{4})$";
The EDI guide specifies a danish post code to be a maximum of 4 characters not exactly 4 characters.

2021-05-26 20:47 UTC, cmgrd requested changes

2021-05-26 20:47 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/AddressMustBeValidRule.cs
> +            When(createMeteringPoint => createMeteringPoint.TypeOfMeteringPoint.Equals(MeteringPointType.Consumption.Name) || createMeteringPoint.TypeOfMeteringPoint.Equals(MeteringPointType.Producti
You could extract a method for the predicate to make it more readable, e.g. MeteringPointTypeIsProductionOrConsumption and use it as a method group. Then it would read `When(MeteringPointTypeIsProductionOrConsumption), () => ...`

2021-05-26 20:47 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/CityNameMaximumLengthMustBeValidRule.cs
> +                .WithState(installationLocationAddress => new CityNameMaximumLengthValidationError(nameof(installationLocationAddress.CityName), MaxCityNameLength));
Same as the former, I don't think we need CityName field name as it's part of the error name, but let's get that confirmed.

2021-05-26 20:47 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/MeteringGridAreaLengthErrorConverter.cs
> +            return new("TODO", $"The metering grid area of a metering point should consist of exactly 3 digits");
For `PostCodeMaximumLengthValidationError` the number was configurable, should it be the same here?

2021-05-27 08:15 UTC, MrDach commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/OccurenceDateMustBeValidRule.cs
> +        private const string OccurenceDateFormatRegEx = @"^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})Z$";
The answer from Ermin is that we should make adding milliseconds optional.

2021-05-27 08:16 UTC, MrDach commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/PostCodeFormatMustBeValidRule.cs
> +        private const string PostCodeDkFormatRegEx = @"^([0-9]{4})$";
The answer from @erduna was that we should stick to exactly 4 characters.

2021-05-28 07:19 UTC, kft submitted a review, later dismissed
Minor comment. Other than, LGTM.

2021-05-28 07:19 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs
> +        private void ValidateCreateMeteringPoint(CreateMeteringPoint businessRequest, System.Type validationError, bool expectedError)
I agree on using "Assert" instead of "Validate".

2021-05-28 07:53 UTC, cmgrd requested changes
Some of the integration tests in CreateTests.cs are failing.

2021-05-28 07:53 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/MeteringGridAreaValidRule.cs
> +                .WithState((createMeteringPoint) => new MeteringGridAreaLengthValidationError(createMeteringPoint.GsrnNumber, createMeteringPoint.MeteringGridArea, ExactGridAreaLengthAllowed));
nit: redundant parentheses

2021-05-28 07:53 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/OccurenceDateMustBeValidRule.cs
> +                .WithState((createMeteringPoint) => new OccurenceDateWrongFormatValidationError(createMeteringPoint.GsrnNumber, createMeteringPoint.OccurenceDate));
nit: redundant parentheses

2021-05-28 07:53 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/PostCodeMandatoryForMeteringPointTypeMustBeValidRuleMustBeValidRule.cs
> +        public PostCodeMandatoryForMeteringPointTypeMustBeValidRuleMustBeValidRule(string gsrnNumber)
typo in name: MustBeValidRuleMustBeValidRule

2021-05-28 07:53 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/PostCodeMandatoryForMeteringPointTypeMustBeValidRuleMustBeValidRule.cs
> +                .WithState(installationLocationAddress => new PostCodeMandatoryForMeteringPointTypeValidationError(gsrnNumber));
Parameter not used, so we could use discard (_) here.

2021-05-28 07:53 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/SettlementMethodMustBeValidRule.cs
> +            When(point => point.TypeOfMeteringPoint.Equals(MeteringPointType.Consumption.Name) || point.TypeOfMeteringPoint.Equals("NetLossCorrection"), () =>
One comparison is strongly typed and the other is a string.
We can extract method for the predicate, as we did in the Address...Rule.

2021-05-31 05:31 UTC, MrDach commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/OccurenceDateMustBeValidRule.cs
> +        private const string OccurenceDateFormatRegEx = @"^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(:\d{2,3})?Z$";
The separator for milliseconds should be "." not ":"

2021-05-31 08:57 UTC, MrDach approved these changes

2021-05-31 09:02 UTC, Korgath approved these changes

2021-05-31 09:11 UTC, merged