Refine MPUpdated contract into several contracts
Energinet-DataHub/geh-metering-point pull request #169
Opened 2021-06-24 11:01 UTC by erduna

The larger MPUpdated contract has been refined with SME into three smaller more relevant contracts which are explicit to what is changed from a business perspective.

Also removed "Message" from the end of a contract name.

## Description

## References

* #0000

2021-06-29 06:32 UTC, cmgrd requested changes

2021-06-29 06:32 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/Contracts/IntegrationEventContract.proto
> +message MeteringPointCreated {
We should probably adhere to the style guide: https://developers.google.com/protocol-buffers/docs/style

2021-06-29 06:32 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/Contracts/IntegrationEventContract.proto
>    string meteringPointType = 2; // Defines the type of metering point created.
As a minimum casing should be consistent.

2021-06-29 10:46 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/Contracts/IntegrationEventContract.proto
>    string meteringPointType = 2; // Defines the type of metering point created.
We actually shouldn't have Gsrn number in our outgoing contracts as it doesn't adhere to entso-e standards, so I will change that too. Later PR for other cases.

2021-06-29 10:48 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/Contracts/IntegrationEventContract.proto
> +message MeteringPointCreated {
You mean snake case for fields?

2021-06-29 10:51 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/Contracts/IntegrationEventContract.proto
> +message MeteringPointCreated {
Yes

2021-06-29 18:18 UTC, Korgath approved these changes

2021-06-29 18:40 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/Contracts/IntegrationEventContract.proto
> +message MeteringPointCreated {
I have just checked other domains, and they do not use snake case either: https://github.com/Energinet-DataHub/geh-post-office/blob/main/source/Contracts/v1/DataAvailable.proto

Should we still use snake case or just fix casing to be consistent?

2021-06-30 10:41 UTC, Korgath approved these changes

2021-06-30 11:15 UTC, cmgrd approved these changes

2021-06-30 14:37 UTC, merged