Connect consumption mp command
Energinet-DataHub/geh-metering-point pull request #172
Opened 2021-07-02 07:37 UTC by Korgath

## Description

- Added HttpTrigger for connect Metering Point
- Added ProtobufMappers for in/outbound connect command
- Added Xml mapper for request
- Added BaseTrigger

## References

* #159

2021-07-02 08:15 UTC, kft requested changes

2021-07-02 08:15 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Application/ConnectMeteringPoint.cs
> +        string Type = "",
What is type ?

2021-07-02 08:15 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Tests/EDI/CreateMeteringPoint/XmlConverterTests.cs
> +            command.Type.Should().Be("E17");
We do not use EDI terms at this level. Why do you need the type anyway ?

2021-07-03 19:49 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Tests/EDI/CreateMeteringPoint/XmlConverterTests.cs
> +            command.Type.Should().Be("E17");
The type is needed for validation rules. As an example can be mentioned the different time parameters depending on if it is a consumption or a production MP

2021-07-03 19:55 UTC, erduna commented
I have reached out to a SME to confirm if mp type is needed to be able to perform all our validations.

2021-07-06 06:20 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/MeteringPointHttpTrigger.cs
> +            catch
Why won't we log the error anymore?

2021-07-06 06:20 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/MeteringPointHttpTrigger.cs
> +            return request.CreateResponse(HttpStatusCode.BadRequest);
Should we give a reason?

2021-07-06 06:20 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Tests/Energinet.DataHub.MeteringPoints.Tests.csproj
> +      <EmbeddedResource Include="EDI\CreateMeteringPoint\ConnectMeteringPointCimXml.xml" />
ConnectMeteringPoint is in CreateMeteringPoint. Maybe move to its own folder.

2021-07-06 06:31 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/MeteringPointHttpTrigger.cs
> +            catch
We are. We are logging it in the dispatch method

2021-07-06 06:43 UTC, kft submitted a review, later dismissed
A couple of comments. Other than that LGTM.

2021-07-06 06:43 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/MeteringPointHttpTrigger.cs
>              }
How do we know if an error should translate to BadRequest ? If an error is thrown, would it not translate to InternalServerError ?

2021-07-06 06:43 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Tests/Application/ConnectMeteringPointMapperTests.cs
> +    }
Should we keep tests like these in codebase ? What's the value ?

2021-07-06 07:10 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/MeteringPointHttpTrigger.cs
> +            return request.CreateResponse(HttpStatusCode.BadRequest);
I don't think so. As I recall the requirement is a Bad Request. 
I don't see why they need to know errors like couldn't deserialize xml or other internals errors

2021-07-06 07:26 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Tests/Application/ConnectMeteringPointMapperTests.cs
> +    }
Confirming your contract mapping. I'm open to not having these tests - could be removed when the entire flow is implemented?

2021-07-06 07:28 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/MeteringPointHttpTrigger.cs
>              }
You are correct - changed to adhere to the old, throwing badrequest on deserialization part, and internal errors on the rest

2021-07-06 07:29 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/MeteringPointHttpTrigger.cs
> +            return request.CreateResponse(HttpStatusCode.BadRequest);
Not sure - As I recall the req is a bad request only?

2021-07-06 08:08 UTC, thbaan approved these changes

2021-07-06 09:38 UTC, erduna approved these changes

2021-07-06 09:49 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/MeteringPointHttpTrigger.cs
> +            catch
But now we have two layers of try/catch, is that better?
Also, I would prefer the logger injected instead of retrieved from the executionContext.

2021-07-06 09:51 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/MeteringPointHttpTrigger.cs
> +            return request.CreateResponse(HttpStatusCode.BadRequest);
But should we say "400: incorrect type/process/something" and 500 if we don't know why?

2021-07-06 10:08 UTC, cmgrd approved these changes

2021-07-06 10:11 UTC, erduna approved these changes

2021-07-06 10:49 UTC, merged