Add TopicSender enabling us to send events to the shared servicebus
Energinet-DataHub/geh-metering-point pull request #186
Opened 2021-07-12 12:33 UTC by Korgath

## Description

- Add TopicSender enabling us to send events to the shared servicebus
- cleanup and refactoring

## References

* #0000

2021-07-12 18:43 UTC, erduna approved these changes

2021-07-13 07:00 UTC, erduna submitted a review, later dismissed

2021-07-13 07:09 UTC, cmgrd requested changes

2021-07-13 07:09 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/EventHandlers/CreateMeteringPointDispatcher.cs
> +    public class CreateMeteringPointDispatcher : IntegrationEventDispatcher<MeteringPointCreatedTopic, MeteringPointCreatedEventMessage>
Namespace/class-suffix mismatch

2021-07-13 07:09 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/EventHandlers/IntegrationEventDispatcher.cs
> +    public abstract class IntegrationEventDispatcher<TTopic, TEvent> : IRequestHandler<TEvent>
Namespace/class-suffix mismatch

2021-07-13 07:09 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/MeteringPointCreatedNotificationHandler.cs
>      public class
I know you didn't touch this line, but that's a weird line break.

2021-07-13 07:26 UTC, cmgrd approved these changes

2021-07-13 07:36 UTC, erduna approved these changes

2021-07-13 07:36 UTC, merged