Dph/validation rules
Energinet-DataHub/geh-metering-point pull request #198
Opened 2021-08-03 12:45 UTC by Korgath

## Description

Following validation rules added:

- If country code is DK then the building number of a metering point consists of maximal 4 characters (range 1-999, A-Z, Æ, Ø, Å capitals only and no spaces), otherwise the building number consists of maximal 6 characters.
- The city sub division name of a metering point consists of maximal 34 characters 
- The municipality code of a metering point consists of exactly 3 digits in the range 100 to 999
- The power plant of a metering point is mandatory for Production MP's
- The power plant of a metering point is mandatory for consumption if their net settlement group is not 0
- The power plant of a metering point is a valid GSRN/EAN18 code (checksum) that starts with digits ´57´

## References

* #0000

2021-08-03 20:04 UTC, cmgrd requested changes

2021-08-03 20:04 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/BuildingNumberFormatMustBeValidRule.cs
> +                .Matches(BuildingNumberDkFormatRegEx)
Nit: Inconsistent use of Dk vs Denmark

2021-08-03 20:04 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs
> +        public void Validate_BuildingNumber_Format(string buildingNumber, string countryCode, System.Type validationError, bool expectedError)
Should "1AAA" validate?

2021-08-04 05:35 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs
> +        public void Validate_BuildingNumber_Format(string buildingNumber, string countryCode, System.Type validationError, bool expectedError)
Yes, since it will comply to the rule

The number range is within 1-999, Max 4 characters, letters are capitals and within A-Z

2021-08-04 09:17 UTC, cmgrd requested changes

2021-08-04 09:17 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/PowerPlantMustBeValidRule.cs
> +                .When(createMeteringPoint => createMeteringPoint.PowerPlant.Length > 0);
Maybe put the When outside these two?

2021-08-04 09:37 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/PowerPlantMustBeValidRule.cs
> +        private static bool ConsumptionAndNetSettlementGroupZero(CreateMeteringPoint createMeteringPoint)
it checks if it is zero?

2021-08-04 10:04 UTC, cmgrd approved these changes

2021-08-04 10:20 UTC, thbaan approved these changes

2021-08-04 10:20 UTC, cmgrd approved these changes

2021-08-04 10:25 UTC, merged