Added input validations for Power Limit
Energinet-DataHub/geh-metering-point pull request #213
Opened 2021-08-06 10:15 UTC by thbaan

## Description

 - The kilowatt power limit of a metering point consists of maximal 6 digits
 - The ampere power limit of a metering point consists of maximal 6 digits

## References

* #0000

2021-08-06 12:33 UTC, Korgath approved these changes

2021-08-09 06:18 UTC, cmgrd requested changes

2021-08-09 06:18 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/PowerLimitErrorConverter.cs
> +            return new("E86", $"Power limit KW {validationError.PowerLimit} for metering point {validationError.GsrnNumber} contains a non-digit character or has a length that exceeds 6");
The message for current seems to differ very slightly (KW -> A), so I don't think we can do with only one error/converter.

![image](https://user-images.githubusercontent.com/459499/128666599-17e2e155-d0ea-4013-bee5-34a028e8e33b.png)

2021-08-09 08:47 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/PowerLimitErrorConverter.cs
> +            return new("E86", $"Power limit KW {validationError.PowerLimit} for metering point {validationError.GsrnNumber} contains a non-digit character or has a length that exceeds 6");
Alternatively we kan ask the business if it is OK to make a more unit agnostic message, eg. "power limit for" instead of "power limit <unit> for".

2021-08-09 13:48 UTC, cmgrd approved these changes

2021-08-09 19:20 UTC, erduna submitted a review, later dismissed
Please merge rules into one, as they both verify the same thing. I have verified with Mogens that we are allowed to perform optimizations like these.

2021-08-09 19:20 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/KilowattPowerLimitValidationError.cs
> +        public KilowattPowerLimitValidationError(string gsrnNumber, string? kilowattPowerLimit)
We have permission from @mogensjuul to merge rules that test the exact same thing into one, and make an error message that is inclusive for both. Eg. not mentioning the unit, but focusing on the restrictions.

2021-08-10 07:40 UTC, Korgath submitted a review, later dismissed

2021-08-10 08:06 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/KilowattPowerLimitValidationError.cs
> +        public KilowattPowerLimitValidationError(string gsrnNumber, string? kilowattPowerLimit)
Actually I started out with one single validation and an associated validation error, but changed it to two specific validation errors since it´s important for users to see which field an error belongs to.

2021-08-10 09:09 UTC, cmgrd approved these changes

2021-08-10 09:09 UTC, Korgath approved these changes

2021-08-10 09:20 UTC, merged