Rule checked for one thing but was called the opposite
Energinet-DataHub/geh-metering-point pull request #260
Opened 2021-08-20 12:13 UTC by erduna

## Description

The rule is checking to verify the MP trying to be created does not already exist. The text stated the opposite, as did the naming of the rule.

## References

* #0000

2021-08-24 06:59 UTC, cmgrd requested changes
Why do we have both `MeteringPointGsrnMustBeUniqueRule` and `MeteringPointMustNotBeKnownRule` ?

2021-08-24 06:59 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/MeteringPointMustNotBeKnownRuleError.cs
> +    public class MeteringPointMustNotBeKnownRuleError : ValidationError
Should be ValidationError instead of RuleError:
```suggestion
    public class MeteringPointMustNotBeKnownValidationError : ValidationError
```

2021-08-24 11:27 UTC, erduna commented
> 
> 
> Why do we have both `MeteringPointGsrnMustBeUniqueRule` and `MeteringPointMustNotBeKnownRule` ?

Fixed. Uniqueness check needed it's own and erroneously used another rules converter.

2021-08-25 10:49 UTC, cmgrd approved these changes

2021-08-25 11:31 UTC, thbaan approved these changes

2021-08-30 11:41 UTC, merged