Add contains to reflection strategy
Energinet-DataHub/geh-metering-point pull request #280
Opened 2021-09-01 14:35 UTC by Sondergaard

## Description

Add two new methods to ReflectionStrategy.
 - ContainsName
 - ContainsValue

They can be used to test if name or value is present within an EnumerationType

## References

Can be used in PR #274

2021-09-02 08:30 UTC, erduna approved these changes

2021-09-03 05:59 UTC, kft submitted a review, later dismissed

2021-09-03 06:26 UTC, MrDach requested changes

2021-09-03 06:26 UTC, MrDach commented on source/Energinet.DataHub.MeteringPoints.Benchmarks/ReflectionStrategies/CheckOnInvocationReflectionStrategy.cs
> +                .FirstOrDefault(item => item.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
Couldn't this be replaced by the following?
`return GetAll<T>().Any(item => item.Name.Equals(name, StringComparison.OrdinalIgnoreCase));`

2021-09-03 06:26 UTC, MrDach commented on source/Energinet.DataHub.MeteringPoints.Benchmarks/ReflectionStrategies/CheckOnInvocationReflectionStrategy.cs
> +            return matchingItem is not null;
Same as above.

2021-09-03 06:44 UTC, Sondergaard commented on source/Energinet.DataHub.MeteringPoints.Benchmarks/ReflectionStrategies/CheckOnInvocationReflectionStrategy.cs
> +            return matchingItem is not null;
Same as above.

2021-09-03 06:48 UTC, erduna approved these changes

2021-09-03 07:43 UTC, MrDach approved these changes

2021-09-03 08:38 UTC, merged