Make meter number nullable
Energinet-DataHub/geh-metering-point pull request #284
Opened 2021-09-02 13:57 UTC by erduna

Meter number needs to be nullable, as it is not allowed for subtypes virtual or calculated

2021-09-02 16:01 UTC, MrDach submitted a review, later dismissed

2021-09-03 07:25 UTC, Korgath approved these changes

2021-09-03 07:31 UTC, cmgrd requested changes

2021-09-03 07:31 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPointHandler.cs
> +                request.MeterNumber!,
! ?

2021-09-03 07:33 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPointHandler.cs
> +                request.MeterNumber!,
It's nullable, thus the !. The other nullables do the same thing

2021-09-03 09:49 UTC, Korgath approved these changes

2021-09-03 11:50 UTC, Sondergaard commented on source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPointHandler.cs
> +                request.MeterNumber!,
This just seems odd. 

With the ! you say I know this is not null. I don't see any statements that checks this assumption. 

If MeterNumber is really nullable as the signature indicates, then the API that receives the value should also accept it as nullable.

2021-09-03 12:24 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPointHandler.cs
> +                request.MeterNumber!,
It's fixed in the subsequent commits, we had a talk offline about the issue :)

2021-09-07 11:45 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/MeterNumberMustBeValidRule.cs
> +                    .WithState(createMeteringPoint => new MeterNumberMaximumLengthValidationError(createMeteringPoint.GsrnNumber, createMeteringPoint.MeterNumber!, MeterNumberMaximumLength));
Should there be a bang here?

2021-09-07 12:27 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/MeterNumberMustBeValidRule.cs
> +                    .WithState(createMeteringPoint => new MeterNumberMaximumLengthValidationError(createMeteringPoint.GsrnNumber, createMeteringPoint.MeterNumber!, MeterNumberMaximumLength));
Yes. Fixed other comments in latest push :)

2021-09-17 07:37 UTC, cmgrd approved these changes

2021-09-20 12:47 UTC, Korgath approved these changes

2021-09-20 12:48 UTC, merged