Refactor: Introduce parameter object for Create-method and handling of scheduled meter reading date
Energinet-DataHub/geh-metering-point pull request #285
Opened 2021-09-07 09:22 UTC by kft

## Description

In this PR:
- Introduced parameter object for Create factory method.
- Added value object and rules for scheduled meter reading date.
- Couple of cleanups

2021-09-07 10:56 UTC, erduna requested changes
Rule for scheduled meter reading date is a bit wrong. When net settlement group is 0 it is not allowed.

2021-09-07 10:56 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/ConsumptionMeteringPointCreated.cs
> +            IsOfficielAddress = isOfficielAddress;
IsOfficialAddress

2021-09-07 10:56 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/Rules/ScheduledMeterReadingDateRule.cs
> +            if (scheduledMeterReadingDate == null) throw new ArgumentNullException(nameof(scheduledMeterReadingDate));
This generally checks if it is missing, but if group is 0 it needs to be null.

2021-09-07 10:56 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
> +        public async Task Should_reject_when_scheduled_meter_reading_date_is_missing()
Only when net settlement group is different than 0. Should not be present when NSG is 0.

2021-09-07 10:56 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Tests/SampleData.cs
> +        public static bool IsOfficielAddress => true;
IsOfficialAddress

2021-09-07 11:42 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPointRuleSet.cs
> +                    .Cascade(CascadeMode.Stop)
Why set CascadeMode to Stop when you're only performing a single validation in this rule?

2021-09-07 11:44 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPointRuleSet.cs
> +                    .Must(value => ScheduledMeterReadingDate.CheckRules(value !).Success)
Can we move this Must statement to the rule above and keep CascadeMode.Stop? Otherwise we are not sure that value are not null

2021-09-07 12:35 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/MeteringPointDetails.cs
> +    public record MeteringPointDetails(
Is this for Consumption metering points only?

2021-09-07 12:39 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/Consumption/CreationTests.cs
> +            // var meteringPointDetails = CreateDetails()
Commented out code

2021-09-08 10:00 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/MeteringPointDetails.cs
> +    public record MeteringPointDetails(
Yes, it's for consumption MP. Hence the namespace.

2021-09-08 10:05 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPointRuleSet.cs
> +                    .Must(value => ScheduledMeterReadingDate.CheckRules(value !).Success)
Sure we can.

2021-09-14 12:02 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
> +        public async Task Should_reject_when_scheduled_meter_reading_date_is_missing()
Actually, scheduled meter reading date is allowed to be set for NSG only according to the SME's. I have updated the business rule accordingly.

2021-09-14 12:03 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/ConsumptionMeteringPointCreated.cs
> +            IsOfficielAddress = isOfficielAddress;
Fixed

2021-09-20 12:27 UTC, Korgath submitted a review, later dismissed

2021-09-21 08:54 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPointHandler.cs
> +                GridAreaId.New(),
Will be handled by the grid area stories.

2021-09-21 09:05 UTC, erduna approved these changes

2021-09-21 10:02 UTC, Korgath approved these changes

2021-09-21 10:08 UTC, merged