Cmgrd/gridareas
Energinet-DataHub/geh-metering-point pull request #335
Opened 2021-09-24 06:38 UTC by cmgrd

## Description

Adds grid areas to the system.

Missing:
- We have left out grid operators for now.

## References

Fixes #296

2021-09-24 11:36 UTC, kft requested changes

2021-09-24 11:36 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/ConsumptionMeteringPoint.cs
> +                new GridAreaMustExistRule(meteringPointDetails.GridAreaId),
The metering point should only require an grid area identifier. Whether or not the grid area exists, should not be a concern of the metering point. So this business rule should be handled at application layer.

2021-09-24 11:36 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
>          [Fact]
Grid area is a general requirement for metering points. Therefore, it could be an idea to move this test to the general test-class instead.

2021-09-27 07:21 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
>          [Fact]
Moved

2021-09-27 08:23 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202109230930 Create Grid Area tables.sql
> +    [Code] NVARCHAR(3) NOT NULL,
is NVARCHAR the best choice considering it can only be 000-999?

2021-09-27 08:23 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/MeteringPointDetails.cs
> +        GridAreaId? GridAreaId,
Why only Id and not also the code?

2021-09-27 08:23 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/GridAreaMustExistRuleErrorConverter.cs
> +            return new("E10", $"A metering point cannot be registered in GEH without a valid identification");
```suggestion
            return new("E10", $"A metering point cannot be registered in GEH without belonging to an existing grid area");
```

2021-09-28 06:01 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/ConsumptionMeteringPoint.cs
> +                new GridAreaMustExistRule(meteringPointDetails.GridAreaId),
Moved

2021-09-28 08:33 UTC, Korgath approved these changes

2021-09-29 05:46 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/MeteringPointDetails.cs
> +        GridAreaId? GridAreaId,
Changed to GridAreaLink

2021-09-29 06:07 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202109230930 Create Grid Area tables.sql
> +    [Code] NVARCHAR(3) NOT NULL,
It could be VARCHAR, but I would probably use NVARCHAR even though it can only be numerics.
Or are you thinking something else entirely?

2021-09-29 06:36 UTC, erduna approved these changes

2021-09-29 06:36 UTC, Korgath approved these changes

2021-09-29 07:05 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202109230930 Create Grid Area tables.sql
> +    [Code] NVARCHAR(3) NOT NULL,
I was thinking NUMERIC(3,0) possibly.

2021-09-29 11:00 UTC, kft approved these changes

2021-09-29 11:01 UTC, merged