Dph/reimplement consumption metering point created ie
Energinet-DataHub/geh-metering-point pull request #344
Opened 2021-09-30 10:34 UTC by Korgath

## Description

- Dispatch consumption metering point created integration events (including refactoring of former method) from the outbox so it complies with the requirements for ADR-008.

Squadron servicebus test not implemented

## References

* #0000

2021-09-30 12:08 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Common/OutboxOrchestrator.cs
> +        private readonly Container _container;
I think it´s bad practice to depend on Container here. Lets say we're changing to another IOC product at a later point, we'll have to refactor this code. If you really wan't to depend on SimpleInjector here, it should be on IServiceProvider and not the specific implementation.

Another aproach could be to inject a factory (e.g. a Func) which could create both a new scope and return an instance of IOutboxMessageDispatcher.

An example that can be used in Composition Root:

`            container.Register(() => OutboxMessageDispatcherFactory(container));
`

`        private static Func<IOutboxMessageDispatcher?> OutboxMessageDispatcherFactory(IServiceProvider container)
        {
            return () =>
            {
                container.CreateScope();
                return container.GetService<IOutboxMessageDispatcher>();
            };
        }`
        
Then you can depend on _Func<IOutboxMessageDispatcher?>_ instead of _IOutboxMessageDispatcher_

2021-09-30 12:11 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Common/OutboxOrchestrator.cs
> +        private readonly Container _container;
... Or could it simply be fixed by making the scope of the IOutboxMessageDispatcher registration transient?

2021-09-30 12:16 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/IntegrationEventDispatcher.cs
> +                ContentType = "application/octet-stream;charset=utf-8",
Could we have this magic string stored somewhere central, so it can be reused?

2021-09-30 12:18 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/MeteringPointConnectedDispatcher.cs
> +            serviceBusMessage.ApplicationProperties.Add("MessageType", "MeteringPointConnected");
nameof(MeteringPointConnected) ?

2021-09-30 12:23 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/Consumption/ConsumptionMeteringPointCreatedIntegrationEventExtension.cs
> +        public static ConsumptionMeteringPointCreated.Types.ProductType GetProductType(
Is it possible to make a generic function that can map EnumerationType to these event specific enums?

2021-09-30 12:26 UTC, cmgrd requested changes

2021-09-30 12:26 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Common/IIntegrationMetaDataContext.cs
> +        public void SetInitialMetaData(Instant timestamp, string? correlationId, Guid eventId);
`Initial`, will it change?

2021-09-30 12:26 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/ConsumptionMeteringPointCreatedDispatcher.cs
> +            serviceBusMessage.ApplicationProperties.Add("MessageType", "ConsumptionMeteringPointCreated");
Some magic is going on here.

2021-09-30 12:26 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/IntegrationEventDispatcher.cs
> +                ContentType = "application/octet-stream;charset=utf-8",
Should we save this somewhere or maybe create a ServiceBusMessageFactory with this predefined?

2021-09-30 12:26 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
> +                Lifestyle.Singleton);
A helper method for these registrations would be nice on the eyes.

2021-09-30 12:26 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/Consumption/ConsumptionMeteringPointCreated.proto
> +  ConnectionState Connection_State = 10; // Denotes which connection state a metering point is created with. For a production metering point this is always "New"
lower_snake_case

2021-09-30 12:26 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/Consumption/OnConsumptionMeteringPointCreated.cs
> +        private async Task<int> GetGridAreaCodeAsync(Guid gridAreaLinkId)
I don't think we should use int. What happens with the 3 digit code, if it's 001?

2021-09-30 12:26 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/Consumption/OnConsumptionMeteringPointCreated.cs
> +            return result ?? throw new InvalidOperationException("Grid Area Code not found");
Is it okay to do the queries directly like this? @kft @thbaan?

2021-09-30 12:26 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Outbox/IOutboxManager.cs
> +        void Add(OutboxMessage message);
There's already an Add method on `IOutbox`, do we need it in both places?

2021-09-30 12:30 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/Consumption/OnConsumptionMeteringPointCreated.cs
> +            return result ?? throw new InvalidOperationException("Grid Area Code not found");
Consulted @kft on this already. same procedure is used in market roles

2021-09-30 12:32 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/Outbox/IOutboxManager.cs
> +        void Add(OutboxMessage message);
Nope

2021-09-30 17:49 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Common/OutboxOrchestrator.cs
> +        private readonly Container _container;
container.Register<IOutboxMessageDispatcher, OutboxMessageDispatcher>(Lifestyle.Transient);

Making this transient instead of scoped also works as you suspected.

2021-10-01 06:42 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Common/EntryPoint.cs
> +                        options.CrossWire<IServiceScopeFactory>();
Why do we need this?

2021-10-01 06:50 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Common/IntegrationEventServiceBusMessageFactory.cs
> +        public ServiceBusMessage EnrichMessage(ServiceBusMessage message, string messageType, int version)
This could be void.

2021-10-01 06:51 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Common/IntegrationEventServiceBusMessageFactory.cs
> +        public ServiceBusMessage EnrichMessage(ServiceBusMessage message, string messageType, int version)
And I think that this could even be an extension so that the factory doesn't modify the object after creation.

2021-10-01 06:54 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Common/EntryPoint.cs
> +                        options.CrossWire<IServiceScopeFactory>();
Leftover from the work surrounding the whole scope issue with outboxdispatcheren - will remove

2021-10-01 07:42 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Common/IntegrationEventServiceBusMessageFactory.cs
> +        public ServiceBusMessage EnrichMessage(ServiceBusMessage message, string messageType, int version)
Resolved as Coop

2021-10-01 11:09 UTC, thbaan approved these changes

2021-10-01 11:22 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
> +                () => new MeteringPointCreatedTopic(
Should we still keep this if we are moving away from the general "MeteringPointCreated" message?

2021-10-01 11:24 UTC, erduna approved these changes

2021-10-01 11:30 UTC, merged