Decompose metering point details
Energinet-DataHub/geh-metering-point pull request #357
Opened 2021-10-04 12:19 UTC by kft

## Description
`MeteringPointDetails` used to be specific for consumption metering points. This PR decomposes into specific classes specific for `MeteringPoint`, `MarketMeteringPoint`, and `ConsumptionMeteringPoint`.

2021-10-04 12:25 UTC, cmgrd approved these changes

2021-10-05 07:46 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPointDetails.cs
> +        PowerLimit PowerLimit,
this is optional
![image](https://user-images.githubusercontent.com/25637982/135981725-9715b734-b3fa-4a0e-85ae-c1dcb0ff52f1.png)

2021-10-05 07:49 UTC, erduna requested changes
Power limits (kwh, ampere) are optional fields. This also means the rules need to be changed so they don't expect them to be present.

2021-10-05 07:49 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MarketMeteringPoints/MeteringPointDetails.cs
> +        PowerLimit PowerLimit,
This is optional
![image](https://user-images.githubusercontent.com/25637982/135981762-9b2afdab-580f-47f7-9438-6729563f4244.png)

2021-10-05 07:55 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPointDetails.cs
> +        PowerLimit PowerLimit,
Will create issue on this not to block this pr, agreed with kft

2021-10-05 07:55 UTC, erduna approved these changes
Will create issue on power limit so as to not block this pr, agreed with kft

2021-10-06 06:33 UTC, merged