Update MessageHub client Package
Energinet-DataHub/geh-metering-point pull request #472
Opened 2021-11-11 10:20 UTC by Korgath

## Description

## References

* #0000

2021-11-11 10:59 UTC, cmgrd submitted a review, later dismissed

2021-11-11 11:27 UTC, cmgrd approved these changes

2021-11-11 11:41 UTC, erduna submitted a review, later dismissed

2021-11-11 13:45 UTC, erduna approved these changes

2021-11-11 13:52 UTC, thbaan approved these changes

2021-11-15 13:24 UTC, Renetnielsen requested changes

2021-11-15 13:24 UTC, Renetnielsen commented on build/infrastructure/main/func-outbox.tf
> +    CHARGES_DEFAULT_MESSAGES_RESPONSE_QUEUE                       = "create-link-messages-reply",
Is this from the shared resources also? If so should be read from KV

2021-11-15 13:24 UTC, Renetnielsen commented on build/infrastructure/main/kv-shared-resources.tf
> +  name         = "kvs-sbq-metering-points-reply-name"
Remove kvs-

2021-11-15 13:24 UTC, Renetnielsen commented on build/infrastructure/main/kv-shared-resources.tf
> +  name         = "kvs-sbq-metering-points-dequeue-name"
Remove kvs-

2021-11-15 13:38 UTC, Renetnielsen approved these changes

2021-11-15 14:21 UTC, erduna approved these changes

2021-11-16 07:50 UTC, merged