Create Special Metering Points
Energinet-DataHub/geh-metering-point pull request #483
Opened 2021-11-17 13:50 UTC by Korgath

## Description

DOES NOT INCLUDE INTEGRATION EVENT

## References

* #0000

2021-11-17 14:51 UTC, MrDach requested changes

2021-11-17 14:51 UTC, MrDach commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Special/SpecialMeteringPoint.cs
> +                throw new ConsumptionMeteringPointException($"Cannot create consumption metering point due to violation of one or more business rules.");
Error message needs to be updated

2021-11-17 19:39 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Special/SpecialMeteringPoint.cs
> +                throw new ConsumptionMeteringPointException($"Cannot create consumption metering point due to violation of one or more business rules.");
Fixed

2021-11-18 07:12 UTC, MrDach approved these changes

2021-11-18 08:22 UTC, cmgrd approved these changes

2021-11-18 08:23 UTC, kft approved these changes
A couple of comment.

2021-11-18 08:23 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Special/Rules/MeterReadingOccurrenceConditionalRule.cs
> +            var t = meteringPointType.Name;
Do not seem to be used

2021-11-18 08:23 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Special/SpecialMeteringPoint.cs
> +        }
Maybe a factory method pr. metering point would be more intention revealing

2021-11-18 08:59 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Special/Rules/MeterReadingOccurrenceConditionalRule.cs
> +            var t = meteringPointType.Name;
Will be handled in another PR

2021-11-18 08:59 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Special/SpecialMeteringPoint.cs
> +        }
Handled in another PR

2021-11-18 08:59 UTC, merged