Update actor and messages
Energinet-DataHub/geh-metering-point pull request #559
Opened 2021-12-16 09:04 UTC by cmgrd

Adds Actor concept and uses this in message generators.

2021-12-16 09:30 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/ActorAccessor.cs
> +            actor.SetRole(role);
What is the purpose of this line ? A getter function should not have side effects

2021-12-16 09:30 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Domain/Actors/Actor.cs
> +        }
I would like to se some tests that describe the purpose and functionality of this logic

2021-12-16 14:59 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/ActorAccessor.cs
> +            actor.SetRole(role);
Removed

2021-12-16 14:59 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Domain/Actors/Actor.cs
> +        }
Removed

2021-12-17 08:06 UTC, Korgath requested changes

2021-12-17 08:06 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/Actors/ActorEntityConfiguration.cs
> +            builder.Ignore("CurrentRole");
According to DC this is obsolete?

2021-12-17 08:33 UTC, Korgath approved these changes

2021-12-17 09:00 UTC, merged