Integration Event Message to EventHub
Energinet-DataHub/geh-metering-point pull request #58
Opened 2021-05-06 11:25 UTC by Korgath

## Description

- Timertrigger function added: EventMessageDispatcher
- Protobuff contract implemented including a dispatcher and channel
- Simpleinjector implemented
- When EF is fully implemented a repository fetching from the Outbox will be added instead of hardcoded object

## References

* #44

2021-05-06 12:03 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/EventMessageDispatcher.cs
> +            logger.LogInformation($"C# Timer trigger function executed at: {DateTimeOffset.UtcNow} (UTC)");
Maybe some more telling info?

2021-05-06 12:03 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/EventMessageDispatcher.cs
> +            logger.LogInformation($"C# Timer trigger function executed at: {DateTimeOffset.UtcNow} (UTC)");
Maybe the dispatched event?

2021-05-06 12:15 UTC, cmgrd requested changes

2021-05-06 12:15 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/CreateMeteringPointHttpTrigger.cs
> +        public async Task<HttpResponseData> RunAsync(
Should this be here?

2021-05-06 12:15 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/IntegrationServices/Mappers/IntegrationEventMessageMapper.cs
> +                    Id = obj.Id, Type = obj.Type, Data = obj.Data,
Nit: I'd prefer newlines.

2021-05-06 12:15 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/IntegrationServices/IntegrationEventMessage.cs
> +    public class IntegrationEventMessage : IOutboundMessage, IInboundMessage
Why inbound?

2021-05-06 12:15 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/IntegrationServices/IntegrationEventMessage.cs
> +        public string? Data { get; set; }
Nullables?

2021-05-06 12:15 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/EventMessageDispatcher.cs
> +            // TODO: Change this to use a repository when EF is implemented
You could consider introducing an application service to orchestrate these.

2021-05-06 12:21 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/EventMessageDispatcher.cs
> +            // TODO: Change this to use a repository when EF is implemented
Yes, this was the plan. Will update TODO to reflect this

2021-05-06 12:27 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/IntegrationContracts/Contract.proto
> +  string data = 3;
Where are these defined?

2021-05-06 12:32 UTC, cmgrd requested changes

2021-05-06 12:32 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/IntegrationContracts/Contract.proto
> +message IntegrationEventMessage {
I think this should be a new proto file as this is another contract

2021-05-07 07:19 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/IntegrationContracts/Contract.proto
> +  string data = 3;
In the Outbox table

2021-05-07 07:23 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/EventMessageDispatcher.cs
> +            logger.LogInformation($"C# Timer trigger function executed at: {DateTimeOffset.UtcNow} (UTC)");
i'll update the logging info, when doing the application service which will be orchestrating this dispatcher

2021-05-07 08:02 UTC, cmgrd requested changes

2021-05-07 08:02 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/IntegrationContracts/IntegrationEventContract.proto
> +  string type = 2;
If defined in the database table how does the client of the contract know about them?

2021-05-17 06:28 UTC, closed without merging