Scheduledmeter reading date format rule update
Energinet-DataHub/geh-metering-point pull request #616
Opened 2022-01-10 13:43 UTC by Korgath

## Description

Scheduledmeter reading date format rule update

## References

* #0000

2022-01-11 08:10 UTC, MrDach approved these changes

2022-01-11 08:11 UTC, MrDach requested changes

2022-01-11 08:11 UTC, MrDach commented on source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Consumption/Rules/ScheduledMeterReadingDateFormatRule.cs
> +            _inputFormat = new Regex(@"(^(--))(\d{2})(-)(\d{2})");
No `$` at the end? :(

2022-01-11 09:31 UTC, MrDach approved these changes

2022-01-12 00:17 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Tests/EDI/ConnectMeteringPoint/ConnectMeteringPointCimXml.xml
> +            <cim:nextReadingDate>--01-01</cim:nextReadingDate>
@kft its the format we have been told by Jan

2022-01-12 00:40 UTC, merged