Input validation - walking skeleton
Energinet-DataHub/geh-metering-point pull request #63
Opened 2021-05-10 07:11 UTC by thbaan

## Description

Walking skeleton for handling of input validation and associated tests

## References

* #0000

2021-05-10 07:25 UTC, kft requested changes

2021-05-10 07:25 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Application/InputValidation/Validators/GsrnInputValidator.cs
> +    }
GSRN format validation is a domain concern. Thus, this should be handled in a GsrnNumber value object residing at domain layer. We can just copy/past that object from MarketRoles bounded context :-)

2021-05-10 07:25 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Application/InputValidation/InputValidationResult.cs
> +            });
Should we not use same `ValidationError` object for all types of validation, so that the `BusinessProcessResponder` only have work with one of type validation error ?

2021-05-10 10:33 UTC, kft approved these changes

2021-05-10 11:08 UTC, erduna requested changes

2021-05-10 11:08 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPoint.cs
>      }
Let's add MeterNumber also, as that is mandatory when the MP is physical, which almost all consumption MPs are.

2021-05-10 11:08 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/InputValidators/OccurenceDateInputValidation.cs
> +            if (!IsValidOccurenceDate(command.OccurenceDate))
Name of this function is not entirely correct, as we are only validating if the format is correct, not if the occurrence date is valid. Validity of occurrence date is based on the specific parameters for a business process. Eg. for Create Metering point it can only be created today or yesterday.

2021-05-10 11:47 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/InputValidators/OccurenceDateInputValidation.cs
> +
Add a TODO about verifying occurrence date is within valid time period

2021-05-10 11:47 UTC, erduna submitted a review, later dismissed

2021-05-11 06:10 UTC, erduna submitted a review, later dismissed

2021-05-12 06:21 UTC, Korgath approved these changes

2021-05-12 06:22 UTC, Korgath approved these changes

2021-05-12 06:24 UTC, erduna approved these changes

2021-05-12 08:01 UTC, merged