Make use of actor middleware
Energinet-DataHub/geh-metering-point pull request #650
Opened 2022-01-19 16:01 UTC by thbaan

2022-01-24 10:48 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/InternalCommands/QueuedInternalCommand.cs
> +        public string CurrentActor { get; }
Fixed.

2022-01-24 12:26 UTC, cmgrd approved these changes

2022-01-24 12:55 UTC, Korgath requested changes

2022-01-24 12:55 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202201180945 Add current actor to internal queue commands.sql
> +    ADD CurrentActor NVARCHAR(MAX) NULL
Is this necessary if you are dropping it immediately after?

2022-01-24 13:23 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202201180945 Add current actor to internal queue commands.sql
> +    ADD CurrentActor NVARCHAR(MAX) NULL
Removed

2022-01-24 13:32 UTC, Korgath submitted a review, later dismissed

2022-01-26 09:58 UTC, MrDach requested changes

2022-01-26 09:58 UTC, MrDach commented on source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Seed/202201181200 Fix actor ids.sql
> +INSERT INTO [dbo].[Actor] ([Id], [IdentificationNumber], [IdentificationType], [Roles])
Are these scripts still relevant after we've implemented the "proper" actor registry?

2022-01-26 11:15 UTC, MrDach approved these changes

2022-01-26 11:19 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Seed/202201181200 Fix actor ids.sql
> +INSERT INTO [dbo].[Actor] ([Id], [IdentificationNumber], [IdentificationType], [Roles])
Reverted.

2022-01-26 13:18 UTC, cmgrd approved these changes

2022-01-26 15:11 UTC, MrDach approved these changes

2022-01-26 15:11 UTC, merged