Mathiesen/daylightsavings
Energinet-DataHub/geh-metering-point pull request #737
Opened 2022-02-14 09:39 UTC by Mathiesen

Validation for EffectiveDate will now take daylight savings into account when validating a date string. 
Unit tests have been changed to reflect this. 

#692

2022-02-16 12:13 UTC, Korgath requested changes

2022-02-16 12:13 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Rules/DateFormatMustBeUTCRule.cs
> +            var tzi = info.IsDaylightSavingTime(parseSuccess);
What does tzi stand for?

2022-02-16 13:08 UTC, cmgrd requested changes

2022-02-16 13:08 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Rules/DateFormatMustBeUTCRule.cs
> +            }
nit: the only thing that changes in the if statement is the format, that could be the only element in the if statement then
```suggestion
            var format = isDaylightSavingTime ? FormatRegExSummer : FormatRegExWinter;
            IsBroken = !Regex.IsMatch(date, format);
```

2022-02-16 13:08 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/Tooling/TestHelpers.cs
> +#pragma warning disable CA1305
What is CA1305? And why is it disabled?

```C#
#pragma warning disable CA1305 // Reason for disabling the rule (reason would also tell what the rule is about)
```

2022-02-16 13:08 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/EffectiveDateTests.cs
> +        public void Create_should_succeed_when_date_format_is_valid_Wierd()
Aren't these the same test methods?

2022-02-16 13:08 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/EffectiveDateTests.cs
> +        //2021-06-06 23:00:00.0000000
Commented out date

2022-02-16 13:08 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Tests/Tooling/TestHelpers.cs
> +#pragma warning disable CA1305
What is CA1305? And why is it disabled?

```C#
#pragma warning disable CA1305 // Reason for disabling the rule (reason would also tell what the rule is about)
```

2022-02-16 13:48 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Rules/DateFormatMustBeUTCRule.cs
> +            var tzi = info.IsDaylightSavingTime(parseSuccess);
tzi = TimeZoneInfo. Remnant from getting things working, it has been changed

2022-02-16 13:50 UTC, Mathiesen commented on source/MeteringPoints.EntryPoints.IntegrationTests/Functions/MeteringPointFunctionAppTests.cs
> +            }
It was to try and catch a more verbose error message. It will be removed before merge.

2022-02-16 13:52 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Rules/DateFormatMustBeUTCRule.cs
> +                out var parseSuccess);
Has been renamed to reflect what type it is

2022-02-16 13:54 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Rules/DateFormatMustBeUTCRule.cs
> +            }
Has been changed. The if statement was for debugging purposes

2022-02-16 13:55 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/Tooling/TestHelpers.cs
> +#pragma warning disable CA1305
CA1305 warns that ToString should contain IFormatProvider. Now it does

2022-02-16 13:55 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/EffectiveDateTests.cs
> +        public void Create_should_succeed_when_date_format_is_valid_Wierd()
Yes had it for debugging purposes

2022-02-16 13:55 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/EffectiveDateTests.cs
> +        //2021-06-06 23:00:00.0000000
Removed

2022-02-16 13:57 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Tests/Tooling/TestHelpers.cs
> +#pragma warning disable CA1305
CA1305 warns that ToString should contain IFormatProvider. Now it does

2022-02-16 14:27 UTC, Korgath submitted a review, later dismissed

2022-02-16 14:51 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/EffectiveDate.cs
> +            }
Is this empty check necessary?

2022-02-16 14:51 UTC, cmgrd commented on source/MeteringPoints.EntryPoints.IntegrationTests/Functions/MeteringPointFunctionAppTests.cs
> +                    .ConfigureAwait(false);
Indentation

2022-02-17 07:28 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/EffectiveDate.cs
> +            }
I don't know the codebase good enough to know if dateInUtc is never null. 
So I would rather be safe and add the check.

2022-02-17 07:29 UTC, Mathiesen commented on source/MeteringPoints.EntryPoints.IntegrationTests/Functions/MeteringPointFunctionAppTests.cs
> +                    .ConfigureAwait(false);
👍

2022-02-17 08:44 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/EffectiveDate.cs
> +            }
I believe the empty check could be changed to

if (dateInUtc == null) throw new ArgumentNullException(nameof(dateInUtc));

dateInUtc = dateInUtc.Trim();

The check rules should catch it if its an empty string

2022-02-17 11:17 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/EffectiveDate.cs
> +            }
Will do

2022-02-17 11:28 UTC, Korgath submitted a review, later dismissed

2022-02-17 12:40 UTC, Korgath requested changes

2022-02-17 12:40 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/EffectiveDate.cs
> +            if (string.IsNullOrEmpty(dateInUtc)) throw new ArgumentNullException(nameof(dateInUtc));
```suggestion
            if (dateInUtc == null) throw new ArgumentNullException(nameof(dateInUtc));
```

2022-02-17 12:40 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/EffectiveDate.cs
> +            if (string.IsNullOrEmpty(dateInUtc)) throw new ArgumentNullException(nameof(dateInUtc));
if the string is empty the DateFormatMustBeUTCRule under checkrules will catch an make sure the correct error message is generated to the reject message instead of throwing it

2022-02-17 12:44 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/EffectiveDate.cs
> +            if (string.IsNullOrEmpty(dateInUtc)) throw new ArgumentNullException(nameof(dateInUtc));
Done and done

2022-02-17 12:55 UTC, Korgath approved these changes

2022-02-17 12:55 UTC, Korgath approved these changes

2022-02-18 12:38 UTC, merged