Create integration point between metering point domain and charge domain
Energinet-DataHub/geh-metering-point pull request #74
Opened 2021-05-17 09:21 UTC by Korgath

## Description

- Integration point implemented (Outbox -> Eventhub)
- Protobuf implemented
- Message dispatcher to dispatch integration event message to Eventhub

## References

* #44

2021-05-18 09:05 UTC, thbaan submitted a review, later dismissed

2021-05-18 09:07 UTC, cmgrd requested changes

2021-05-18 09:07 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Tests/Outbox/IntegrationEventTests.cs
> +            _outboxMessageNoIdCTOR = new(
What does NoIdCTOR mean?

2021-05-18 09:07 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Tests/Repositories/IntegrationEventRepositoryTests.cs
> +    public class IntegrationEventRepositoryTests
Missing Traits?

2021-05-18 10:14 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Tests/Outbox/IntegrationEventTests.cs
> +            _outboxMessageNoIdCTOR = new(
@cmgrd  that is an outboxmessage object created using the constructor with no ID input

2021-05-18 10:20 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Tests/Repositories/IntegrationEventRepositoryTests.cs
> +    public class IntegrationEventRepositoryTests
Good catch  ( :

2021-05-18 10:36 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Tests/Repositories/IntegrationEventRepositoryTests.cs
> +                "12345678",
We should use a valid gsrn so it can be pass yet to be implemented validations. Eg. (571234567891234605)
```suggestion
                "571234567891234605",
```

2021-05-18 10:36 UTC, erduna approved these changes

2021-05-18 10:43 UTC, Korgath commented on source/Energinet.DataHub.MeteringPoints.Tests/Repositories/IntegrationEventRepositoryTests.cs
> +                "12345678",
Fair enough :)

2021-05-18 11:19 UTC, thbaan approved these changes

2021-05-18 12:02 UTC, merged

2021-05-19 06:13 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Tests/Outbox/IntegrationEventTests.cs
> +            _outboxMessageNoIdCTOR = new(
I think you should call it that then :)