Dph/integration event handler#72
Energinet-DataHub/geh-metering-point pull request #82
Opened 2021-05-19 09:33 UTC by Korgath

## Description

Metering Point Created notification handler implemented
Dummy class MeteringPointCreated added untill domain base events is implemented

## References

* #72

2021-05-19 09:55 UTC, cmgrd requested changes

2021-05-19 09:55 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPointCreated.cs
> +    // Dummy class until domain base events are implemented.
Can we add TODO? That way it's easier to track.

2021-05-19 09:55 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/PublishWhenMeteringPointIsCreated.cs
> +    public class PublishWhenMeteringPointIsCreated : INotificationHandler<MeteringPointCreated>
How should we name notification handlers?
Maybe a better name would be something like `MeteringPointCreatedNotificationHandler`?

2021-05-19 10:05 UTC, kft requested changes
A comment around domain events vs. integration events.

2021-05-19 10:05 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/PublishWhenMeteringPointIsCreated.cs
> +    public class PublishWhenMeteringPointIsCreated : INotificationHandler<MeteringPointCreated>
But you could have multiple notification handlers handling the same domain event. So, bring out the intent of the handler in the naming seems to me to be the way to go about it.

2021-05-19 10:05 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/PublishWhenMeteringPointIsCreated.cs
> +}
Is `MeteringPointCreated`not the domain event ? If so, we should define a integration event, and parse relevant values from the domain event. Domain events should never leave the bounded context, even though the integration event might be quite similar. It is to different concepts.

2021-05-19 10:11 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/PublishWhenMeteringPointIsCreated.cs
> +    public class PublishWhenMeteringPointIsCreated : INotificationHandler<MeteringPointCreated>
So maybe `PublishMeteringPointIsCreatedHandler`? I would like to add the handler part - otherwise it sounds like an event itself to me.

2021-05-19 13:11 UTC, erduna approved these changes

2021-05-25 11:31 UTC, erduna approved these changes

2021-05-25 11:31 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Domain/Events/CreateMeteringPointEventMessage.cs
> +            EnergySupplierCurrent = energySupplierCurrent;
EnergySupplier is irrelevant now, I'll make a new list

2021-05-25 11:31 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/IntegrationServices/Dispatchers/MeteringPointCreatedNotificationHandler.cs
> +                true,
Why is this set to true?

2021-05-25 11:31 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/IntegrationServices/Dispatchers/MeteringPointCreatedNotificationHandler.cs
> +                true,
agreed this will default to false until we have implemented MPs that can be childs.

2021-05-25 13:38 UTC, cmgrd requested changes

2021-05-25 13:38 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Infrastructure/IntegrationServices/Repository/IIntegrationEventRepository.cs
>          Task MarkIntegrationEventMessageAsProcessedAsync(Guid id);
Is the (I)IntegrationEventRepository still in use?

2021-05-25 13:38 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Domain/Events/CreateMeteringPointEventMessage.cs
> +        public string MpType { get; }
MeteringPointType?

2021-05-25 13:38 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
> +
nit: remove space to indicate that Send and Process are both part of the Act section of the test.

2021-05-25 13:38 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
> +            // _container.Register<CreateMeteringPointEventMessageHandlerTestDispatcher>(Lifestyle.Scoped);
Remove

2021-05-25 19:08 UTC, erduna approved these changes

2021-05-26 07:10 UTC, thbaan submitted a review, later dismissed

2021-05-26 07:14 UTC, cmgrd submitted a review, later dismissed

2021-05-26 07:18 UTC, cmgrd submitted a review, later dismissed

2021-05-26 07:22 UTC, thbaan submitted a review, later dismissed

2021-05-26 08:08 UTC, thbaan approved these changes

2021-05-26 08:09 UTC, cmgrd approved these changes

2021-05-26 08:12 UTC, merged