Mathiesen/disconnect on child mps
Energinet-DataHub/geh-metering-point pull request #835
Opened 2022-04-29 07:52 UTC by Mathiesen

## Description

## References

* #0000

2022-05-02 13:00 UTC, kft requested changes

2022-05-02 13:00 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/Scenarios.cs
>          {
Why not use the type ?

2022-05-03 07:00 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/Scenarios.cs
>          {
Because I have a test that uses inline data and that can't take a type

2022-05-03 10:06 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/DisconnectionTypeValidator.cs
> +
Changed

2022-05-04 08:18 UTC, kft requested changes

2022-05-04 08:18 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Domain/Extensions/MeteringPointTypeStringExtensions.cs
> +}
What is the purpose of this ?

2022-05-04 08:18 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Components/DisconnectionType.cs
>      }
This value object should not know anything about either GSRN numbers or metering point type. Whether or not Disconnection type is required, should be handled in the validation set for the specific metering point type.

2022-05-04 08:18 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Rules/DisconnectionTypeIsValidRule.cs
> +}
Same as above

2022-05-04 08:18 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Rules/DisconnectionTypeMandatoryRule.cs
> +}
Same as above

2022-05-04 08:18 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/SpecialMeteringPointTests.cs
> +                };
Test should be defined for the specific metering point type

2022-05-04 08:22 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Domain/Extensions/MeteringPointTypeStringExtensions.cs
> +}
To make sure that the meteringpoint in question is either E17, E18 or E20

2022-05-04 09:10 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/SpecialMeteringPointTests.cs
> +                };
So you want me to create the same test multiple times?

2022-05-04 09:13 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/SpecialMeteringPointTests.cs
> +                };
I have moved it to CreateTests putting it in a more general place

2022-05-04 09:21 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Domain/Extensions/MeteringPointTypeStringExtensions.cs
> +}
Deleted

2022-05-04 09:43 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Components/DisconnectionType.cs
>      }
Changed

2022-05-04 09:43 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Rules/DisconnectionTypeIsValidRule.cs
> +}
Ditto

2022-05-04 09:43 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Rules/DisconnectionTypeMandatoryRule.cs
> +}
Ditto

2022-05-04 11:47 UTC, Mathiesen commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/SpecialMeteringPointTests.cs
> +                };
Done

2022-05-04 13:24 UTC, kft approved these changes
Just one comment regarding a test. Other than LGTM.

2022-05-04 13:24 UTC, kft commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
>          private static CreateMeteringPoint CreateCommand()
This should not be needed, since it is already tested at domain layer (unit test)

2022-05-04 16:41 UTC, merged