Xkama/validation input settlementmethod
Energinet-DataHub/geh-metering-point pull request #86
Opened 2021-05-19 21:34 UTC by xnetsrak

## Description

Added Input validation rule for SettlementMethod.
Test added.
SettlementMethod ValidationErrors added.

## References

* #71

2021-05-20 05:43 UTC, cmgrd requested changes

2021-05-20 05:43 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs
> +        public void Validate_MandatorySettlementMethodForConsumptionAndNetLossCorrectionMeteringType(string meteringPointType, string settlementMethod, bool expectedError)
I think we should test for a specific error - otherwise how do we know if we test each error?

2021-05-20 07:40 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/SettlementMethodMustBeValidRule.cs
> +                    .Must(settlementMethod => settlementMethod.Contains("NonProfiled") || settlementMethod.Contains("Flex"))
Why are you using Contains for string comparison? I´d suggest to declare an array of valid values and use Contains on that instead.

2021-05-20 13:45 UTC, xnetsrak commented on source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/SettlementMethodMustBeValidRule.cs
> +                    .Must(settlementMethod => settlementMethod.Contains("NonProfiled") || settlementMethod.Contains("Flex"))
Changed to use contains on list. I expect changes again when we find "correct" test values and refactor for better naming.

2021-05-20 15:31 UTC, thbaan approved these changes

2021-05-21 11:48 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs
> +        [Theory]
We're missing a trait at top of this class, otherwise all good :)

2021-05-21 11:54 UTC, erduna approved these changes

2021-05-21 12:59 UTC, Korgath approved these changes

2021-05-21 13:07 UTC, merged