Supporting multiple types of Metering Points
Energinet-DataHub/geh-metering-point pull request #95
Opened 2021-05-20 15:30 UTC by thbaan

## Description

## References

* #0000

2021-05-20 15:49 UTC, cmgrd approved these changes

2021-05-20 15:49 UTC, cmgrd commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
> +            CleanupDatabase(_serviceProvider.GetService<MeteringPointContext>());
I think we should do this after the container is configured, right now it's not a problem because it's the service provider and not container.

Also we cleanup both before and after, is that necessary?

2021-05-21 07:09 UTC, kft submitted a review, later dismissed

2021-05-21 07:42 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPointHandler.cs
> +                SystemClock.Instance.GetCurrentInstant(), // TODO: how to handle string to Instant conversion?
Why do we have 2 instanced of get current instant? One of these should be reading the occurrence as sent in with the request and validating the requested occurrence to see if it is within the correct timeframe for allowing MP creation?

2021-05-21 07:44 UTC, erduna requested changes
See comments

2021-05-21 07:44 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPointHandler.cs
> +                SystemClock.Instance.GetCurrentInstant(), // TODO: how to handle string to Instant conversion?
And the first is meter reading occurrence? That is not system clock either, but either PT15M, PT1H or P1M (for certain Mps)

2021-05-21 07:45 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
> +        public Instant? MeterReadingOccurrence { get; }
not instant

2021-05-21 07:46 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
> +        public Instant? OccurenceDate { get; }
not instant, but provided upon request

2021-05-21 07:46 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ProductionMeteringPoint.cs
> +            Instant? meterReadingOccurrence,
Not instant. Same for all "instant" cases in the PR

2021-05-21 07:48 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
> +                OccurenceDate = DateTime.Now.ToString(CultureInfo.CurrentCulture),
These 2 are not date times

2021-05-21 07:52 UTC, erduna commented on source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
> +                OccurenceDate = DateTime.Now.ToString(CultureInfo.CurrentCulture),
Well, the reading occurrence is not. The OccurrenceDate is, but it is provided in the request and not something we set.

2021-05-21 07:55 UTC, thbaan commented on source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPointHandler.cs
> +                SystemClock.Instance.GetCurrentInstant(), // TODO: how to handle string to Instant conversion?
Did you read the TODO comment? ;)

2021-05-21 08:05 UTC, erduna approved these changes
Approved with agreement that comments are revisited in followup PR

2021-05-21 13:27 UTC, kft submitted a review, later dismissed

2021-05-25 06:02 UTC, cmgrd approved these changes

2021-05-25 06:37 UTC, Korgath approved these changes

2021-05-25 06:38 UTC, merged